"""Add canonical_name to observations

Revision ID: 305f4933c10b
Revises: 6610f7f9625c
Create Date: 2026-01-06 16:54:43.173292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305f4933c10b'
down_revision: Union[str, Sequence[str], None] = '6610f7f9625c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('canonical_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'canonical_name')
    # ### end Alembic commands ###
