"""Add site_name to observations

Revision ID: 6610f7f9625c
Revises: 549c9b319622
Create Date: 2026-01-06 15:53:20.133276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6610f7f9625c'
down_revision: Union[str, Sequence[str], None] = '549c9b319622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('site_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'site_name')
    # ### end Alembic commands ###
