"""add fetch_type column

Revision ID: f6c3e3180d38
Revises: 305f4933c10b
Create Date: 2026-01-07 10:42:44.977320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c3e3180d38'
down_revision: Union[str, Sequence[str], None] = '305f4933c10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('fetch_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'fetch_type')
    # ### end Alembic commands ###
