"""Initial global catalog: the real products from the v0 configuration.

Each item has a friendly name, category, package, search aliases and an explicit,
deterministic matching rule. Images are original illustrations shipped with the
project (``seed/images/<slug>.svg``), so nothing depends on hotlinked assets.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

from pricetracker.models.enums import SoldBy, Unit

SEED_IMAGE_LICENSE = "Ilustração original do projeto PriceTracker (MIT)"

_PROCESSED_GRAINS = [
    "pronto", "pronta", "cozido", "cozida", "enlatado", "enlatada", "conserva", "sopa",
    "caldo", "creme", "farinha", "biscoito", "salgadinho", "snack", "congelado",
]  # fmt: skip

CATALOG: list[dict[str, Any]] = [
    {
        "slug": "arroz-branco-1kg",
        "name": "Arroz branco 1 kg",
        "category": "Grãos e cereais",
        "description": "Arroz branco tipo 1, pacote de 1 kg.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.KG,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "match_spec": {
            "search_terms": ["arroz branco 1kg", "arroz 1kg", "arroz"],
            "required": [["arroz"]],
            "excluded": [
                "integral",
                "parboilizado",
                "arboreo",
                "japones",
                "basmati",
                "jasmim",
                "negro",
                "vermelho",
                "selvagem",
                "cateto",
                "7 graos",
                "grega",
                "bolinho",
                "doce",
                "risoto",
                "mistura",
                *_PROCESSED_GRAINS,
            ],
            "sold_by": "package",
            "size": {"quantity": "1", "unit": "kg", "tolerance_pct": "0"},
        },
    },
    {
        "slug": "feijao-1kg",
        "name": "Feijão 1 kg",
        "category": "Grãos e cereais",
        "description": "Feijão carioca ou preto, pacote de 1 kg.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.KG,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "match_spec": {
            "search_terms": ["feijão 1kg", "feijão preto 1kg", "feijão carioca 1kg"],
            "required": [["feijao"]],
            "excluded": [
                "feijoada",
                "tropeiro",
                "branco",
                "fradinho",
                "bolinha",
                "jalo",
                "rajado",
                "vermelho",
                "azuki",
                "moyashi",
                "verde",
                "corda",
                "manteiga",
                "tempero",
                *_PROCESSED_GRAINS,
            ],
            "sold_by": "package",
            "size": {"quantity": "1", "unit": "kg", "tolerance_pct": "0"},
        },
    },
    {
        "slug": "lentilha-400g",
        "name": "Lentilha 400 g",
        "category": "Grãos e cereais",
        "description": "Lentilha seca, pacote de 400 g.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("400"),
        "package_unit": Unit.G,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "match_spec": {
            "search_terms": ["lentilha 400g", "lentilha"],
            "required": [["lentilha"]],
            "excluded": ["vermelha", "rosa", "beluga", "coral", "salada", *_PROCESSED_GRAINS],
            "sold_by": "package",
            "size": {"quantity": "400", "unit": "g", "tolerance_pct": "0"},
        },
    },
    {
        "slug": "ovos-30-unidades",
        "name": "Ovos 30 unidades",
        "category": "Ovos e frios",
        "description": "Cartela ou bandeja com 30 ovos de galinha.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("30"),
        "package_unit": Unit.UN,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "match_spec": {
            "search_terms": ["ovos 30 unidades", "ovos"],
            "required": [["ovo"]],
            "excluded": [
                "codorna",
                "chocolate",
                "pascoa",
                "liquido",
                "po",
                "desidratado",
                "cozido",
            ],
            "sold_by": "package",
            "size": {"quantity": "30", "unit": "un", "tolerance_pct": "0"},
        },
    },
    {
        "slug": "alcatra-kg",
        "name": "Alcatra (kg)",
        "category": "Carnes",
        "description": "Alcatra bovina vendida por quilo.",
        "sold_by": SoldBy.WEIGHT,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.KG,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.KG,
        "match_spec": {
            "search_terms": ["alcatra", "alcatra bovina"],
            "required": [["alcatra"]],
            "excluded": [
                "moida",
                "hamburguer",
                "espeto",
                "empanado",
                "temperada",
                "marinada",
                "tempero",
                "frango",
                "suina",
                "linguica",
                "almondega",
            ],
            "sold_by": "weight",
            "max_piece_kg": "3",
        },
    },
    {
        "slug": "maminha-kg",
        "name": "Maminha (kg)",
        "category": "Carnes",
        "description": "Maminha bovina vendida por quilo.",
        "sold_by": SoldBy.WEIGHT,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.KG,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.KG,
        "match_spec": {
            "search_terms": ["maminha", "maminha bovina"],
            "required": [["maminha"]],
            "excluded": ["moida", "espeto", "temperada", "marinada", "tempero", "frango", "suina"],
            "sold_by": "weight",
            "max_piece_kg": "3",
        },
    },
    {
        "slug": "cafe-tres-coracoes-gourmet-sul-de-minas-250g",
        "name": "Café Três Corações Gourmet Sul de Minas 250 g",
        "category": "Café e chás",
        "description": "Café torrado e moído Três Corações Gourmet Sul de Minas, 250 g.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("250"),
        "package_unit": Unit.G,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "brand": "Três Corações",
        "match_spec": {
            "search_terms": [
                "café três corações gourmet sul de minas 250g",
                "café 3 corações sul de minas",
            ],
            "required": [["cafe"], ["gourmet"], ["sul de minas"]],
            "excluded": [
                "capsula",
                "capsulas",
                "sache",
                "soluvel",
                "graos",
                "descafeinado",
                "drip",
            ],
            "brands": ["três corações", "3 corações", "tres coracoes"],
            "strict_brand": True,
            "sold_by": "package",
            "size": {"quantity": "250", "unit": "g", "tolerance_pct": "0"},
        },
    },
    {
        "slug": "filtro-cafe-102",
        "name": "Filtro de café 102",
        "category": "Café e chás",
        "description": "Filtro de papel tamanho 102, caixa com cerca de 30 unidades.",
        "sold_by": SoldBy.PACKAGE,
        "package_quantity": Decimal("30"),
        "package_unit": Unit.UN,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.PCT,
        "match_spec": {
            "search_terms": ["filtro de café 102", "filtro papel 102"],
            "required": [["filtro"], ["102"]],
            "excluded": [
                "permanente",
                "reutilizavel",
                "pano",
                "porta filtro",
                "suporte",
                "coador",
                "103",
            ],
            "sold_by": "package",
            "size": {"quantity": "30", "unit": "un", "tolerance_pct": "35"},
        },
    },
    {
        "slug": "maca-fuji-kg",
        "name": "Maçã Fuji (kg)",
        "category": "Hortifrúti",
        "description": "Maçã Fuji vendida por quilo.",
        "sold_by": SoldBy.WEIGHT,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.KG,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.KG,
        "match_spec": {
            "search_terms": ["maçã fuji", "maçã fuji kg"],
            "required": [["maca"], ["fuji"]],
            "excluded": [
                "suco",
                "desidratada",
                "chips",
                "polpa",
                "doce",
                "geleia",
                "vinagre",
                "cha",
            ],
            "sold_by": "weight",
            "max_piece_kg": "3",
        },
    },
    {
        "slug": "mamao-papaia-unidade",
        "name": "Mamão papaia (unidade)",
        "category": "Hortifrúti",
        "description": "Mamão papaia (papaya) vendido por unidade.",
        "sold_by": SoldBy.UNIT,
        "package_quantity": Decimal("1"),
        "package_unit": Unit.UN,
        "default_quantity": Decimal("1"),
        "default_unit": Unit.UN,
        "match_spec": {
            "search_terms": ["mamão papaia", "mamão papaya"],
            "required": [["mamao"], ["papaia", "papaya"]],
            "excluded": ["formosa", "polpa", "suco", "desidratado", "doce", "vitamina"],
            "sold_by": "unit",
            "approx_unit_weight_kg": "0.45",
        },
    },
]

CATEGORY_PLACEHOLDERS: dict[str, str] = {
    "Grãos e cereais": "placeholder-graos",
    "Ovos e frios": "placeholder-frios",
    "Carnes": "placeholder-carnes",
    "Café e chás": "placeholder-cafe",
    "Hortifrúti": "placeholder-hortifruti",
    "Mercearia": "placeholder-mercearia",
    "Laticínios": "placeholder-laticinios",
    "Bebidas": "placeholder-bebidas",
    "Limpeza": "placeholder-limpeza",
    "Higiene": "placeholder-higiene",
    "Padaria": "placeholder-padaria",
    "Outros": "placeholder-outros",
}
CATEGORIES = list(CATEGORY_PLACEHOLDERS)
